# Generated by Django 4.0.6 on 2023-03-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateTest', '0006_student_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
