# Generated by Django 4.0.6 on 2023-03-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateTest', '0007_student_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
