# Generated by Django 4.0.6 on 2023-03-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generateTest', '0008_alter_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='accepting_response',
            field=models.BooleanField(default=True),
        ),
    ]
